version: '3.0'

networks:
  wp_network:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

services:
  nginx:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=site.local
    depends_on:
      - php
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./html/:/var/www/html/
    networks:
      wp_network:
        ipv4_address: 172.21.0.2

  php:
    build:
      context: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./html/:/var/www/html/
    networks:
      wp_network:
        ipv4_address: 172.21.0.3

  mysql:
    image: mariadb:10.6.8
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      wp_network:
        ipv4_address: 172.21.0.4

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    environment:
#      - VIRTUAL_HOST=phpmyadmin.local
#      - PMA_HOST=mysql
#      - PMA_USER=root
#      - PMA_PASSWORD=root
#    networks:
#      wp_network:
#        ipv4_address: 172.21.0.5

